# Generated by Django 5.2.3 on 2025-06-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Sets the birth day of the user', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Sets the first name of the user', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not specified')], default='N', help_text='Sets the gender of the user', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='isPrivateProfile',
            field=models.BooleanField(default=False, help_text='Sets the user profile to private, (Privacy Related)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Sets the last name of the user', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, help_text='Sets the phone number of the user', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Sets the first username of the user', max_length=150, unique=True),
        ),
    ]
