# Generated by Django 5.2.3 on 2025-06-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
